### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by RebelnetRSA** [bcombs18/osTicket-Inventory-Manager#56]
Hi

I followed the installation instructions but receive a HTTP ERROR 500 when accessing the Inventory Manager from the Agent Panel.
Is there any additional steps I perhaps missed?

My installation details are in the attached file.

Regards

![image](https://user-images.githubusercontent.com/110462227/182351040-d43d9653-4816-4bdb-b839-d46054db532c.png)

**Comment by bcombs18** [comment]
Hello @RebelnetRSA, I believe you are seeing this error because you are running PHP 8.1 on your osTicket instance. The inventory plugin does not currently support PHP 8.1, PHP 8.0 is the recommended version. I suggest downgrading your PHP version and reinstalling the plugin.

osTicket v1.16.x should have no issues running on PHP 8.0 so there should be no side affects with downgrading.

**Comment by RebelnetRSA** [comment]
Hi 

Thank you for the prompt response. I've dropped the PHP version as below with the same result.

When selecting the Inventory manager from the Agent Panel, I am redirected to the following URL: 
www.mydomain/osticket/scp/dispatcher.php/inventory/asset/handle
I have even uninstalled osticket completely and reinstalled from scratch to see if it would help

![image](https://user-images.githubusercontent.com/110462227/182462804-cbb98476-0caf-4d52-a8ee-ccb688743966.png)

**Comment by RebelnetRSA** [comment]
Hi

Thank you for the prompt response. I've dropped the PHP version as below with the same result.


When selecting the Inventory manager from the Agent Panel, I am redirected to the following URL:
(http://www.mydomain/osticket/scp/dispatcher.php/inventory/asset/handle)

I have even uninstalled osticket completely and reinstalled from scratch to see if it would help

![image](https://user-images.githubusercontent.com/110462227/182463097-7390dc5d-2e02-47cb-97b5-e44b468214d5.png)

**Comment by bcombs18** [comment]
Okay, that is the correct URL for accessing the plugin. Can you post your php_error log? That will give me a better idea of what's failing here.

**Comment by RebelnetRSA** [comment]
Hi

Hope this is what you are looking for. I haven't messed around with this sort of thing for around 10 years.
[PHP_Errors.txt](https://github.com/bcombs18/osTicket-Inventory-Manager/files/9245541/PHP_Errors.txt)

**Comment by bcombs18** [comment]
That's it! Looks like there is some issue with retrieving the Inventory Form from the database. When you did the initial setup for osTicket and entered the configuration for the database, do you remember if you left the "table prefix" option default to "ost_" or changed it to something else? I may have hard-coded that prefix in the Inventory form which could potentially be throwing the error.

**Comment by RebelnetRSA** [comment]
Ah yes. I did leave the table prefix.

It is set to ostq4_

I noticed when reinstalling that installing osTicket through Softaculous adds a random prefix.

Should I try reinstalling with a prefix of ost_ ?

**Comment by bcombs18** [comment]
Okay, that's the issue. I can confirm that I did hard code that to use "ost_". You can either reinstall and use "ost_" as the prefix, or you can open the "AssetForm.php" file located in osTicket-Inventory-Manager-1.1.0/include/model/ and edit line 10. Change it from "'table' => 'ost_form'," to "'table' => TABLE_PREFIX.'form',". Don't include the double quotes.

I will work on getting that fix released soon, it will be available most likely by next week.

**Comment by RebelnetRSA** [comment]
Ok, I've amended the table prefix and ost-config file and its working now.

Thank you so much for your assistance!

![image](https://user-images.githubusercontent.com/110462227/182478326-725df2d1-00a7-4c99-a441-cdc5bd448263.png)

**Comment by bcombs18** [comment]
My pleasure! Thanks for reporting the issue. Don't hesitate to let me know if you run into other problems!
